### PR TITLE
Switch to esprima-next

### PR DESCRIPTION
**Pull request by Puyb**
Esprima is no longer maintained. Esprima-next fixes a lot of bugs

### CODE REVIEW

**Comment by azu** [comment]
Can you remove lib/ dir from file changed?

```
git rm lib/
```

These files should be ignored
https://github.com/azu/ast-source/blob/06932b170e3c0b0242c2a5f3395b58a50979b7df/.gitignore#L84

**Comment by Puyb** [comment]
You're right. I added the lib folder because the module wasn't working when I was adding the package using npm with the git url.

I've now added a "prepare" script that is launched automatically when adding the package to build it.

**Comment by azu** [comment]
Thanks!
Release 
https://github.com/azu/ast-source/releases/tag/v4.0.0

**Comment by Puyb** [comment]
Wonderful! Thank you for your work!

**Pull request merged**
